### ISSUE TITLE
No new images?

### ISSUE THREAD

**Issue by staniek** [appimage-packages/kexi#7]
Hi!
There were changes in kexi.git, yet I see no new nightly snapshots built. Are those enabled for every night? Is there anything that could be fixed?

**Comment by ScarlettGatelyMoore** [comment]
Apologies, in a bit of a tooling refactor/merge into bluesystems tools. This is why we have not gone completely public with our appimages, still a WIP. It is building now, and feel free to ping me if it does not build. Sorry!

**Comment by star-buck** [comment]
Yes, this is mainly for evaluation and testing various software and
packaging requirements, so not anything official yet.

**Comment by staniek** [comment]
I understand and appreciate!

**Comment by staniek** [comment]
Hi, May I ask for a new Appimage build? Thanks.

**Comment by staniek** [comment]
Something else: kexi-git20170405-x86_64.AppImage and some other files are only 300KB large. Broken or?

**Comment by ScarlettGatelyMoore** [comment]
Yes, tooling is going through a major refactor. I will try to have a new build for you by end of today.

**Comment by staniek** [comment]
Hi! The newest snapshot is from May 07. Any issues?

**Comment by star-buck** [comment]
Hi Jaroslaw,

the autogenerate appimage server was ever only a testing system, not
production. Any resulting images were fine as they were. Since the
beginning of May Scarlett has been reassigned to other tasks, so she cant
productively maintain any test results anymore. I will update the
description of this repo to reflect the status change.
We will evaluate the results so far and then decide if pursuing this on a
grander scale makes sense or if other venues like TravisCi ate better
suited due to sharing or reusing others work makes more sense.
For now, this project is dormant for above reasons until a decision to
continue has been made.
Greetings, Clemens.

**Comment by staniek** [comment]
Thanks for the update, Clemens. That's fine, we will try to continue from this point based on scripts available. I am going to add Blue Systems to the list of supporters in Kexi about box if you're OK with that :)
Big thanks for the support!

And thanks @ScarlettGatelyClark for your dedication.

**Comment by star-buck** [comment]
@staniek : really appreciated, but no need to give bluesystems credit.
If you want though go ahead with mentioning Scarlett helping you with some Kexi Appimage stuff :)

**Comment by staniek** [comment]
Done: https://cgit.kde.org/kexi.git/commit/?id=233e1d7e4b0f7666eb88b431a6db2908aa65a49e

Happy birthday Scarlett :)

**Comment by ScarlettGatelyMoore** [comment]
Thanks!
